services:
    #Application service: PHP, Apache and Node
    application:
        container_name: todo-app
        build:
            context: .
        ports:
            -  "80:80"
        networks:
            - app-network
        depends_on:
            -   mysql-db

    #Database server
    mysql-db:
        container_name: todo-app-db
        image: mysql:8.0
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            -   "3306:3306"
        networks:
            - app-network
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/mysql

networks:
    app-network:
        driver: bridge

volumes:
    db-data:
